source 'https://rubygems.org'

gem 'bootsnap', '~> 1.23', require: false
gem 'devise', '~> 5.0'
gem 'devise-jwt', '~> 0.13'
gem 'pg', '~> 1.6'
gem 'puma', '~> 7.2'
gem 'rack-cors', '~> 3.0'
gem 'rails', '~> 8.1.2'
gem 'redis', '~> 5.4'
gem 'sidekiq', '~> 8.1'
gem 'sidekiq-cron', '~> 2.3'
gem 'tzinfo-data', platforms: %i[windows jruby]

group :development, :test do
  gem 'brakeman', require: false
  gem 'bundler-audit', require: false
  gem 'debug', platforms: %i[mri windows], require: 'debug/prelude'
  gem 'factory_bot_rails', '~> 6.4'
  gem 'faker', '~> 3.5'
  gem 'rspec-rails', '~> 7.1'
  gem 'rubocop-factory_bot', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
end

group :test do
  gem 'database_cleaner-active_record', '~> 2.2'
  gem 'shoulda-matchers', '~> 6.4'
  gem 'simplecov', '~> 0.22', require: false
  gem 'timecop', '~> 0.9'
  gem 'webmock', '~> 3.24'
end
